name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build-n-publish:
    name: Build and publish Python package
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # required for Trusted Publishers
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI using Trusted Publisher
        uses: pypa/gh-action-pypi-publish@v1.9.0
